#!/usr/bin/env bash
# a Bash script that will display information about subdomains


display()
{
	line=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -1) 
	echo "$2 $line" | awk '{print "The subdomain " $1 " is a "$5" record and points to " $6}'
}

if [ "$#" -eq 1 ]
then
	display "$1" "www"
	display "$1" "lb-01"
	display "$1" "web-01"
	display "$1" "web-02"
elif [ "$#" -eq 2 ]
then
	display "$1" "$2"
fi
