#!/usr/bin/env bash
# a bash script that transfers a file from our client to a server

if [ $# -lt 4 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	filePath=$1
	serverIP=$2
	username=$3
	sshKey=$4

	scp -i "$sshKey" -o StrictHostKeyChecking=no "$filePath" "$username@$serverIP":~/
fi
