#!/usr/bin/env bash
# installs nginx
sudo apt-get update
sudo apt-get -y install nginx

#configures nginx to print hello world
echo 'Hello World!' | sudo tee /var/www/html/index.html
service nginx start
