#!/usr/bin/env bash
# a bash script that installs and configures nginx server on ubuntu

# install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# configure nginx
mkdir /etc/nginx/html

# create sample page
echo "Hello World!" > /etc/nginx/html/index.html

# create server block files
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /etc/nginx/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;
}
" > /etc/nginx/sites-available/default

# restart nginx
nginx -s reload

# output
echo '["Hello World!"]'
