#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

# install nginx
sudo apt-get update
sudo apt-get install -y nginx


new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
