#!/usr/bin/env bash
# configure nginx and adding an http response

sudo apt-get -y update
sudo apt-get -y install nginx

# adding http resonse
sudo sed -i "47i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# adding pages
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo service nginx start
