#!/usr/bin/env bash
# Bash script to install and configure haproxy.

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo chown -R ubuntu /etc/haproxy

# configure front and back ends
sudo echo "
frontend web_frontend
        bind *:80
        mode http
        default_backend web_backend
backend web_backend
        balance roundrobin
        server 160785-web-01 3.84.239.114:80 check
        server 160785-web-02 34.224.17.58:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
